[package]
name = "kusuo"
version = "0.1.0"
authors = ["ariwaranosai <nkssai@outlook.com>"]

[lib]
name = "kusuo_lib"
path = "src/lib/lib.rs"

[[bin]]
name = "kusuo"
path = "src/bin/kusuoc.rs"
doc = false

[dependencies]
nom = "^3.2"
clap = "~2.31"